
service:
  venocl.elrte:
    class: Venocl\ElrteBundle\Form\Type\ElrteType
    arguments:
      options:
        lang         : fr
        styleWithCSS : false
        height       : 400
        toolbar      : maxi
