
services:
  venocl.form.type.elrte:
      class: Venocl\ElrteBundle\Form\Type\ElrteType
      arguments:
        options:
          toolbar: normal
      tags:
          - { name: form.type, alias: venocl_elrte }

